# TODO: troubleshoot travis locally
# https://docs.travis-ci.com/user/common-build-problems/#Troubleshooting-Locally-in-a-Docker-Image
git:
  depth: 3
sudo: required
services:
  # TODO: what version of docker is travis running
  - docker
language: java # default is oracle JDK 1.8.0_151
jdk:
  - oraclejdk8
# TODO: build matrix for different database and benchmarks
# https://docs.travis-ci.com/user/environment-variables/#Defining-Multiple-Variables-per-Item
env:
  - TEST=TPCC DB=MYSQL
  - TEST=TPCC DB=POSTGRES
  - TEST=TPCH DB=MYSQL
  - TEST=TPCH DB=POSTGRES
# https://stackoverflow.com/questions/34377017/what-are-the-differences-between-the-before-install-script-travis-yml-opti
before_install:
  - java -version
  - docker version
  - docker-compose version
  # check if common ports are already in use ...
  - sudo netstat -nlp | grep :3306
  - sudo netstat -nlp | grep :5432
  - if [ "$DB" == 'MYSQL' ]; then sudo service mysql stop; fi
  - if [ "$DB" == 'POSTGRES' ]; then sudo service postgresql stop; fi
# https://docs.travis-ci.com/user/database-setup/#Multiple-Database-Builds
install:
  - if [ "$DB" == 'MYSQL' ]; then docker-compose -f docker/mysql.yml up -d; fi
  - if [ "$DB" == 'POSTGRES' ]; then docker-compose -f docker/postgres.yml up -d; fi
script:
  - echo "${TEST} ${DB}"
after_script:
  - if [ "$DB" == 'MYSQL' ]; then docker-compose -f docker/mysql.yml down; fi
  - if [ "$DB" == 'POSTGRES' ]; then docker-compose -f docker/postgres.yml down; fi