# TODO: troubleshoot travis locally
# https://docs.travis-ci.com/user/common-build-problems/#Troubleshooting-Locally-in-a-Docker-Image
git:
  depth: 3
sudo: required
services:
  # TODO: what version of docker is travis running
  - docker
language: java
# TODO： just use one jdk?
#jdk:
#  - oraclejdk8
#  - openjdk8
# TODO: build matrix for different database and benchmarks
env:
  - TEST=TPCC
  - TEST=TPCH
matrix:
  include:
    - env: DB=MYSQL
    - env: DB=POSTGRES
# https://stackoverflow.com/questions/34377017/what-are-the-differences-between-the-before-install-script-travis-yml-opti
before_install:
  - java -version
  - docker version
  - docker-compose version
install:
  - if [ $DB == MYSQL ]; docker-compose -f docker/mysql.yml up -d
  - if [ $DB == POSTGRES]; docker-compose -f docker/postgres.yml up -d
script:
  - echo "${TEST} ${DB}"
after_script:
  - if [ $DB == MYSQL ]; docker-compose -f docker/mysql.yml down
  - if [ $DB == POSTGRES]; docker-compose -f docker/postgres.yml down