git:
  depth: 3
sudo: required
services:
  - docker
language: java # default is oracle JDK 1.8.0_151
jdk:
  - oraclejdk8
addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"
# TODO: build matrix for different database and benchmarks
# https://docs.travis-ci.com/user/environment-variables/#Defining-Multiple-Variables-per-Item
env:
  - BENCH=tpcc DB=mysql
  - BENCH=tpcc DB=postgres
  - BENCH=tpcc DB=tidb
  # - BENCH=tpcc DB=memsql
  - BENCH=epinions DB=mysql
  - BENCH=tatp DB=mysql
  - BENCH=ycsb DB=mysql
  - BENCH=voter DB=mysql
  # - BENCH=auctionmark DB=mysql 
  - BENCH=wikipedia DB=mysql
  - BENCH=seats DB=mysql
  - BENCH=sibench DB=mysql
  - BENCH=noop DB=mysql
  - BENCH=smallbank DB=mysql
  - BENCH=twitter DB=mysql
  - BENCH=resourcestresser DB=mysql
  - BENCH=ycsb DB=cassandra
  # - BENCH=TPCH DB=mysql
  # - BENCH=TPCH DB=postgres
# https://stackoverflow.com/questions/34377017/what-are-the-differences-between-the-before-install-script-travis-yml-opti
before_install:
  - python3 --version
  - sudo pip3 install pyyaml
  - java -version
  - docker version
  - docker-compose version
  # check if common ports are already in use, travis starts a bunch of DBMS by default ....
  - sudo netstat -nlp | grep :3306
  - sudo netstat -nlp | grep :5432
  - sudo service mysql stop
  - sudo service postgresql stop
# https://docs.travis-ci.com/user/database-setup/#Multiple-Database-Builds
install:
  - ant build
  - ./docker/travis_start.sh
before_script:
  - ./config/config.py validate
script:
  - ./config/config.py generate --bench ${BENCH} --db ${DB} --scalefactor 1
  - ./oltpbenchmark --bench ${BENCH} --config config/generated_${BENCH}_${DB}_config.xml --create true --load true --execute true
after_script:
  - ./docker/travis_stop.sh