# list of benchmarks supported by oltpbench in alphabetical order
# benchmark name
auctionmark:
  # displayname
  name: AuctionMark
  # short description
  description: A benchmark from H-Store
  # shorter names
  alias:
    - auction
  # original homepage url, could be dead ...
  url: http://hstore.cs.brown.edu/projects/auctionmark/
  # list of contributions in time order
  contributions:
    - time: TODO: time format
      author: 
      url:
chbenchmark:
  name: CH-benCHmark
  description: A mix of TPC-C and TPC-H run in parallel on a single DBMS
  alias:
    - ch
    - mix
  url: https://db.in.tum.de/research/projects/CHbenCHmark/?lang=en
epionions:
  name: Epinions
  description: Epinions.com was a general consumer review site established in 1999. Epinions was acquired by Shopping.com in 2003, which in turn was acquired by eBay in 2005
  alias:
    - epion
    - epionion
    - consumer-review
  url: http://www.epinions.com/
hyadapt:
  name: HyAdapt
  description: TODO
  alias:
    - hyadap
  url: https://github.com/oltpbenchmark/oltpbench
jpab:
  name: JPAB
  description: Java Persistence API Performance Benchmark
  alias:
    - jpba
  url: http://www.jpab.org/
linkbench:
  name: LinkBench
  description: a Database Benchmark Based on the Facebook Social Graph
  alias:
    - fbgraph
  url: http://people.cs.uchicago.edu/~tga/pubs/sigmod-linkbench-2013.pdf
noop:
  name: Noop
  description: no table, no query, just SELECT 1;
  alias:
    - nop
  url: https://github.com/oltpbenchmark/oltpbench
resourcestresser:
  name: ResourceStresser
  description: Synthetic Resource Stresser meaningless but CPU/IO heavy statements
  alias:
    - stress
  url: https://github.com/oltpbenchmark/oltpbench
seats:
  name: SEATS
  description: Buy airplane tickets
  alias:
    - plane
  url: https://github.com/oltpbenchmark/oltpbench
sibench:
  name: SIBench
  description: Snapshot Isolation
  alias:
    - si
  # link dead
  url: http://sydney.edu.au/engineering/it/~fekete/teaching/serializableSI-Fekete.pdf
smallbank:
  name: SmallBank
  description: A bank with only three tables accounts, saving and checking
  alias:
    - sb
  url: https://ses.library.usyd.edu.au/bitstream/2123/5353/1/michael-cahill-2009-thesis.pdf
TODO: still some left ....  tatp, tpcc, tpcds, tpch, twitter, voter, wikipedia, ycsb