# list of databases in alphabetical order
mysql:
  name: MySQL
  driver: com.mysql.jdbc.Driver
  port: 3306
  username: root
  password: oltpbenchpassword
postgres:
  name: PostgreSQL
  alias:
    - postgresql
    - pg
  driver: org.postgresql.Driver
  port: 5432
  username: oltpbench
  password: oltpbenchpassword