# list of databases in alphabetical order
mysql:
  name: MySQL
  driver: com.mysql.jdbc.Driver
  port: 3306
  username: root
  password: oltpbenchpassword
  # TODO: docker and local installation may use different default user and pwd
postgres:
  name: PostgreSQL
  alias:
    - postgresql
    - pg
  driver: org.postgresql.Driver
  port: 5432
  # NOTE: this is needed because database name is postgres instead of postgresql
  dburl: "jdbc:postgresql://{host}:{port}/{db}"
  username: oltpbench
  password: oltpbenchpassword